export const PLANS = {
  free: {
    id: 'free',
    name: 'Free',
    slug: 'free',
    priceMonthly: 0,
    priceAnnual: 0,
    limits: {
      transcriptionMinutes: 60,
      storageGB: 1,
      meetings: 10,
      exports: 5,
      aiTokens: 100000,
      teamMembers: 1,
    },
    features: [
      'Basic transcription',
      'AI-powered notes',
      'Action items extraction',
      'Meeting search',
      '1GB storage',
      '60 transcription minutes/month',
      'PDF exports',
    ],
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    slug: 'pro',
    priceMonthly: 9.99,
    priceAnnual: 99.99,
    limits: {
      transcriptionMinutes: 500,
      storageGB: 10,
      meetings: 100,
      exports: 50,
      aiTokens: 1000000,
      teamMembers: 1,
    },
    features: [
      'Everything in Free',
      '500 transcription minutes/month',
      '10GB storage',
      'Advanced AI analysis',
      'DOCX exports',
      'Google integrations',
      'Priority support',
    ],
  },
  business: {
    id: 'business',
    name: 'Business',
    slug: 'business',
    priceMonthly: 29.99,
    priceAnnual: 299.99,
    limits: {
      transcriptionMinutes: 2000,
      storageGB: 100,
      meetings: 1000,
      exports: 500,
      aiTokens: 10000000,
      teamMembers: 50,
    },
    features: [
      'Everything in Pro',
      'Team collaboration',
      '2000 transcription minutes/month',
      '100GB storage',
      'Admin dashboard',
      'Team management',
      'API access',
      'Custom branding',
      'SSO',
      'Priority support',
    ],
  },
};

export type PlanKey = keyof typeof PLANS;
